### ISSUE TITLE
why does this try to make a symlink on install?

### ISSUE THREAD

**Issue by seiyria** [oprogramador/random-weighted-item#3]
I ran `npm i random-weighted-item` and it tried to run your symlink script. please remove it.

**Comment by piotr-s-brainhub** [comment]
why?
doesn’t it work?

**Comment by seiyria** [comment]
No, and you shouldn't be running scripts like that when a user installs
anyway

**Comment by oprogramador** [comment]
are you using Windows?

I checked this symlink works both on Linux and Mac

**Comment by seiyria** [comment]
Yes, I am, but there is no reason for this script to exist, period. It's especially unnecessary when I install it.

**Comment by oprogramador** [comment]
the reason is I can use absolute path in imports ex. https://github.com/oprogramador/random-weighted-item/blob/master/src/index.js#L1

**Comment by seiyria** [comment]
That's not the right way to do that. Use `import getRandomItem from './getRandomItem'`. Also, you should be compiling the code before pushing it to npm, because this isn't necessarily valid (`export default` in particular is not standard). Also, if it's just one file, there's no reason to not just pull it all in to index.js.

**Comment by oprogramador** [comment]
it's compiled with babel

**Comment by seiyria** [comment]
Then there is definitely no reason for that symlink script to run when I install your library. It's extremely sketchy. And, regardless, you shouldn't be doing absolute imports anyway.

**Comment by oprogramador** [comment]
this https://github.com/tleunen/babel-plugin-module-resolver seems to work fine

**Comment by oprogramador** [comment]
@seiyria this library no longer uses symlinks so it should work in your environment
